# ========================
# Essentials

misc:
  path: misc

logger:
  path: logger

i18n:
  path: i18n

eventBus:
  path: eventbus

db:
  path: database/mongodb
  inject: ['config', 'logger']

db.models:
  path: database/models
  inject: ['db']

web.server:
  path: web/server
  inject: ['config', 'logger']

web.accessLogger:
  path: web/accessLogger
  inject: ['web.server']

web.common:
  path: web/common
  inject: ['web.server']

web.session:
  path: web/session
  inject: ['web.server', 'config', 'db']

web.security:
  path: web/security
  inject: ['web.server', 'config']

web.static:
  path: web/static
  inject: ['web.server']

web.templateEngine:
  path: web/templateEngine
  inject: ['web.server', 'config']

# ========================
# Business Services

userService:
  path: business/user
  inject: ['eventBus', 'db']

announcementService:
  path: business/announcement
  inject: ['eventBus', 'db']

challengeService:
  path: business/challenge
  inject: ['eventBus', 'db']

contestService:
  path: business/contest
  inject: ['eventBus', 'db']

# ========================
# Presentation Layer

web.controllers:
  path: web/controllers
  inject: ['web.server', 'logger']
